name: Assign Next Release Milestone

on:
  pull_request:
    types:
      - closed

jobs:
  assign:
    name: Assign Milestone
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: sv-tools/create-milestone-action@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Next Release'
        continue-on-error: true
      - uses: zoispag/action-assign-milestone@v1.1.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          milestone: 'Next Release'
